### ISSUE TITLE
feature request: full genome sequences

### ISSUE THREAD

**Issue by jvolkening** [NDVconsortium/NDV_Sequence_Datasets#1]
Kiril et al,

This is a great way to share the latest classifications. I was wondering if it would be possible to add to the repo the FASTA of full genome sequences (with new classifications) that was used to generate Fig. S6 in the paper?

**Comment by NDVconsortium** [comment]
Hi Jeremy, 
The complete genome dataset is available upon request.  After discussions, we have decided to not upload it here to avoid confusion as only the use of complete fusion gene coding sequences is recommended for classification purposes.  The complete genome tree is provided only as a comparison to the complete fusion tree and to demonstrate the possibilities of its future use to revisit the current classification when sufficient complete genomes from all sub/genotypes become available.
Thank you!
-Kiril Dimitrov
